"""The window where a freshly deployed box answers anybody.

`gateway/auth.py` has a branch for local development: with **no accounts yet** and **no
gateway token**, it returns without checking anything. That is right on a laptop and
dangerous on a public URL, because the window closes only when the first account is
registered — by whoever registers first, which on a public URL need not be the owner.

Nothing in the application can tell a laptop from a public host, so this is not fixed in
code; it is fixed in deployment, by never letting the token be unset. `render.yaml` uses
`generateValue: true` for both secrets so Render mints them at create time. These tests pin
both halves: the behaviour, so it is understood rather than rediscovered, and the blueprint,
so the mitigation cannot quietly be dropped back to `sync: false`.
"""

import pathlib

import yaml
from fastapi.testclient import TestClient

from gateway.main import create_app

OPEN_WHEN_EMPTY = ("/v1/today", "/v1/graph", "/v1/people")


def _fresh(cfg, token=""):
    cfg = {**cfg, "gateway": {"auth_token": token}}
    return TestClient(create_app(cfg))


def test_a_fresh_box_with_no_token_answers_anybody(cfg):
    """Documented, not desired. If this ever starts failing, the local-dev branch changed
    and `render.yaml`'s comment needs rewriting with it."""
    client = _fresh(cfg)
    for path in OPEN_WHEN_EMPTY:
        assert client.get(path).status_code == 200, path


def test_the_first_registration_closes_it(cfg):
    client = _fresh(cfg)
    client.post("/v1/auth/register",
                json={"handle": "firstcomer", "password": "correct-horse-battery"})
    for path in OPEN_WHEN_EMPTY:
        assert client.get(path).status_code == 401, path


def test_a_token_closes_it_before_anybody_registers(cfg):
    """The property the blueprint relies on: set the token and there is no open window."""
    client = _fresh(cfg, token="a-gateway-token-for-this-suite-only")
    for path in OPEN_WHEN_EMPTY:
        assert client.get(path).status_code == 401, path


def test_render_generates_both_secrets_rather_than_leaving_them_unset():
    """`sync: false` only means "not in the blueprint" — a service still starts without a
    value. `generateValue` makes the unset state unreachable."""
    blueprint = yaml.safe_load(
        (pathlib.Path(__file__).resolve().parent.parent / "render.yaml").read_text())
    env = {v["key"]: v for s in blueprint["services"] for v in s.get("envVars", [])}
    for key in ("LIFEOS_SIGNING_KEY", "LIFEOS_GATEWAY_TOKEN"):
        assert env[key].get("generateValue") is True, (
            f"{key} must be generated by Render, not left for somebody to remember")
        assert "value" not in env[key], f"{key} must never carry a literal in the blueprint"


def test_the_two_generated_secrets_are_separate_entries():
    """They are different values because they are generated independently. The signing key
    blinds dating matching as well as signing payloads, so reusing the owner's bearer token
    as that key would leak one into the other."""
    blueprint = yaml.safe_load(
        (pathlib.Path(__file__).resolve().parent.parent / "render.yaml").read_text())
    keys = [v["key"] for s in blueprint["services"] for v in s.get("envVars", [])]
    assert keys.count("LIFEOS_SIGNING_KEY") == 1
    assert keys.count("LIFEOS_GATEWAY_TOKEN") == 1
