"""Coach LLM Rewording Pass (Phase 1b).

Optional server-side pass that rewords deterministic coach proposal copy
using Claude into warm, encouraging phrasing — with zero-key offline fallback.
"""

import json
import logging

logger = logging.getLogger(__name__)

SYSTEM_PROMPT = """You are an encouraging LifeOS coach assistant.
You will be given a JSON array of proposal cards generated by deterministic rules.
Your task is to reword the 'body' string of each proposal card to make it warm, empathetic, and motivating.

CRITICAL INVARIANTS:
1. Do NOT invent new proposals or remove existing ones.
2. Do NOT alter any numbers, metrics, or factual statements.
3. Return ONLY a JSON array of objects, where each object has 'id' (matching the original proposal id) and 'body' (the reworded text).
"""


def reword_proposals(proposals: list[dict], claude_gateway=None) -> list[dict]:
    """Rewords proposal bodies if Claude is available; returns original proposals otherwise."""
    if not proposals:
        return []

    if claude_gateway is None or not getattr(claude_gateway, "enabled", False):
        return proposals

    # Prepare lightweight payload for Claude
    input_data = [
        {"id": p.get("id"), "title": p.get("title", ""), "body": p.get("body", ""), "evidence": p.get("evidence", "")}
        for p in proposals
    ]

    try:
        user_prompt = f"Please reword these proposals:\n{json.dumps(input_data, indent=2)}"
        res_text = claude_gateway.prompt(SYSTEM_PROMPT, user_prompt)
        
        # Clean potential markdown formatting
        cleaned = res_text.strip()
        if cleaned.startswith("```json"):
            cleaned = cleaned[7:]
        if cleaned.startswith("```"):
            cleaned = cleaned[3:]
        if cleaned.endswith("```"):
            cleaned = cleaned[:-3]
        
        reworded_list = json.loads(cleaned.strip())
        reword_map = {item["id"]: item.get("body") for item in reworded_list if "id" in item and "body" in item}

        out = []
        for p in proposals:
            p_copy = dict(p)
            pid = p_copy.get("id")
            if pid in reword_map and reword_map[pid]:
                p_copy["body"] = reword_map[pid]
            out.append(p_copy)
        return out
    except Exception as exc:
        logger.warning(f"Coach LLM rewording failed, falling back to original proposals: {exc}")
        return proposals
